### ISSUE TITLE
Unable to build in windows

### ISSUE THREAD

**Issue by last-Programmer** [anowell/wkhtmltopdf-rs#6]
I am  trying to use the library in windows console application. I am not able to build successfully. This is the error i am getting

`/lowlevel.rs:92: undefined reference to `wkhtmltopdf_init'`

i have the build.rs search for the library.

```
fn main() {
    println!(r"cargo:rustc-link-search=C:\Program Files\wkhtmltopdf\lib");
}
```

even after doing that i am getting the error.

Any help would be appreciated.

Thank You

**Comment by tamasfe** [comment]
The library is still dynamically linked to `wkhtmltox.dll` which has to be present in the path so that windows can find it at runtime. It is found in `wkhtmltopdf/bin/wkhtmltox.dll`.

I just copied it to system32, but having it in the path or the work dir where you run the application should be enough.

**Comment by craigmayhew** [comment]
Closing ticket due to inactivity. Thanks @tamasfe for the help you provided back in 2020!
